application:
  css:
    theme:
      node_modules/@fortawesome/fontawesome-free/css/all.css: {}
      theme/css/bootstrap.min.css: {}
      theme/css/style.css: {}
      theme/css/table-style.css: {}
      theme/css/icon-font.min.css: {}
      css/style.css: {}
  js:
    js/application.js: {}
  dependencies:
    - core/jquery
    - core/drupal
    - core/jquery.ui
    - core/jquery.ui.widget
    - core/jquery.ui.draggable
    - core/jquery.ui.mouse
    - core/jquery.ui.position
    


accueil:
  css:
    theme:
      css/accueill.css: {}
      
      
user_login:
  css:
    theme:
      node_modules/@fortawesome/fontawesome-free/css/all.css: {}
      css/bootstrap.css: {}
      theme-user/css/style.css: {}
      css/profil.css: {}
  js:
    theme-user/js/canva_custom.js: {}
    theme-user/js/canva_moving_effect.js: {}
  dependencies:
    - core/drupal