application:
  css:
    theme:
      css/fontawesome/web-fonts-with-css/css/fontawesome-all.min.css: {}
      css/style.css: {}
  js:
    js/jquery-3.7.1.min.js: {}
    js/application.js: {}
  dependencies:
    - core/drupal

user_login:
  css:
    theme:
      css/bootstrap.css: {}
      theme-user/css/style.css: {}
      theme-user/css/fontawesome-all.css: {}
      css/profil.css: {}
  js:
    theme-user/js/canva_custom.js: {}
    theme-user/js/canva_moving_effect.js: {}
  dependencies:
    - core/drupal