name: application
type: theme
description: "ITIETOGO Theme"
core_version_requirement: ^9 || ^10
base theme: bootstrap

logo: logo.png
screenshot: screenshot.png

regions:
  navigation    : 'Navigation'
  header        : 'Top Bar'
  highlighted   : 'Highlighted'
  help          : 'Help'
  menu_main     : 'Main menu'
  content       : 'Content'
  sidebar_first : 'Side bar first'
  sidebar_second : 'side bar second'
  footer        : 'Footer'
  page_top      : 'Page top'
  page_bottom   : 'Page bottom'
# On charge les librairies de manieres dynamiques.
# libraries:
#  - application/application


