stdClass Object
(
    [nid] => 62
    [uid] => 59291
    [sid] => 
    [submitted] => 1532348043
    [completed] => 0
    [modified] => 1532348043
    [remote_addr] => 41.202.207.9
    [is_draft] => 0
    [highest_valid_page] => 0
    [preview] => 
    [serial] => 
    [data] => Array
        (
            [1] => Array
                (
                    [0] => 
                )

            [2] => Array
                (
                    [0] => 
                )

            [3] => Array
                (
                    [0] => 
                )

            [4] => Array
                (
                    [0] => 
                )

            [5] => Array
                (
                    [0] => 
                )

            [6] => Array
                (
                    [0] => 
                )

            [7] => Array
                (
                    [addnewfile_wbu] => Array
                        (
                            [fichiers_joins_wbu] => Array
                                (
                                    [buttonmore] => ajouter un fichier
                                    [0] => 92
                                    [1] => 93
                                    [2] => 94
                                )

                            [_weight] => 0
                        )

                    [0] => 95
                )

        )

)
