stdClass Object
(
    [nid] => 62
    [uid] => 0
    [sid] => 
    [submitted] => 1546416816
    [completed] => 0
    [modified] => 1546416816
    [remote_addr] => 77.57.157.70
    [is_draft] => 0
    [highest_valid_page] => 0
    [preview] => 
    [serial] => 
    [data] => Array
        (
            [1] => Array
                (
                    [0] => Guide Cloud
                )

            [2] => Array
                (
                    [0] => Constant
                )

            [3] => Array
                (
                    [0] => 
                )

            [4] => Array
                (
                    [0] => awudi@sogesti.fr
                )

            [5] => Array
                (
                    [0] => 
                )

            [6] => Array
                (
                    [0] => 
                )

            [7] => Array
                (
                    [addnewfile_wbu] => Array
                        (
                            [fichiers_joins_wbu] => Array
                                (
                                    [buttonmore] => ajouter un fichier
                                )

                            [_weight] => 0
                        )

                    [0] => 97
                )

        )

)
